def get_name_info(name):
    # Dummy etymology data
    sample_etymology = {
        "Alice": "Alice is of Old French origin meaning 'noble'.",
        "John": "John is of Hebrew origin meaning 'God is gracious'.",
        "Sophia": "Sophia is of Greek origin meaning 'wisdom'.",
        "Leo": "Leo is of Latin origin meaning 'lion'.",
        "Emma": "Emma is of German origin meaning 'universal' or 'whole'.",
        "Michael": "Michael is of Hebrew origin meaning 'who is like God?'.",
        "Olivia": "Olivia is of Latin origin meaning 'olive tree'.",
        "James": "James is of Hebrew origin meaning 'supplanter'.",
        "Isabella": "Isabella is of Hebrew origin meaning 'pledged to God'.",
        "Benjamin": "Benjamin is of Hebrew origin meaning 'son of the right hand'.",
        "Topher": "Topher is a short form of Christopher meaning 'bearer of Christ'.",
        "Afsana": "Afsana is of Persian origin meaning 'story' or 'fable'.",
        "Zara": "Zara is of Arabic origin meaning 'princess' or 'flower'.",
        "Kian": "Kian is of Irish origin meaning 'ancient'.",
        "Layla": "Layla is of Arabic origin meaning 'night' or 'darkness'.",
        "Nia": "Nia is of Swahili origin meaning 'purpose'.",
        "Ravi": "Ravi is of Sanskrit origin meaning 'sun'.",
        "Zoe": "Zoe is of Greek origin meaning 'life'.",
        "Liam": "Liam is of Irish origin meaning 'strong-willed warrior'.",
        "Mia": "Mia is of Italian origin meaning 'mine' or 'beloved'.",
        "Noah": "Noah is of Hebrew origin meaning 'rest' or 'comfort'.",
        "Ava": "Ava is of Latin origin meaning 'life'.",
        "Ethan": "Ethan is of Hebrew origin meaning 'strong' or 'firm'.",
        "Tiffany": "Tiffany is of Greek origin meaning 'appearance of God'.",
        "Jason": "Jason is of Greek origin meaning 'healer'.",
        "Sean": "Sean is of Irish origin meaning 'God is gracious'.",
        "Destiny": "Destiny is of Latin origin meaning 'fate' or 'fortune'.",
        "Bernice": "Bernice is of Greek origin meaning 'bringer of victory'.",
        "Gab": "Gabriel is of Hebrew origin meaning 'God is my strength'.",
        "Khalil": "Khalil is of Arabic origin meaning 'friend' or 'companion'.",
        "Devin": "Devin is of Irish origin meaning 'poet' or 'fawn'.",
        "Kyle": "Kyle is of Scottish origin meaning 'narrow channel' or 'strait'.",
        "Bella": "Bella is of Italian origin meaning 'beautiful'.",
        "Edward": "Edward is of Old English origin meaning 'wealthy guardian'.",
        "Gertrude": "Gertrude is of German origin meaning 'spear of strength'.",
        "Hannah": "Hannah is of Hebrew origin meaning 'grace' or 'favor'.",
        "Isaac": "Isaac is of Hebrew origin meaning 'laughter'.",
        "Julia": "Julia is of Latin origin meaning 'youthful' or 'downy'.",
        "Kevin": "Kevin is of Irish origin meaning 'handsome' or 'kind'.",
        "Laura": "Laura is of Latin origin meaning 'laurel' or 'victory'.",
        "Marcus": "Marcus is of Latin origin meaning 'warlike'.",
        "Nora": "Nora is of Latin origin meaning 'honor' or 'light'.",
        "Oscar": "Oscar is of Irish origin meaning 'deer lover' or 'friend of deer'.",
        "Asha": "Asha is of Sanskrit origin meaning 'hope' or 'wish'.",
        }
    return sample_etymology.get(name, f"No etymology info found for {name}.")